
[font]
size = 15.0

[font.bold]
style = "Medium"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[terminal.shell]
args = ["-l", "-c", "/opt/homebrew/bin/tmux attach || /opt/homebrew/bin/tmux || zsh"]
program = "/opt/homebrew/bin/zsh"

[window.padding]
x = 3
y = 7

[general]
import = ["~/.config/alacritty/dracula.toml"]

[terminal]

[env]
LC_CTYPE = "C.UTF-8"
LANG = "C.UTF-8"
